### ISSUE TITLE
Support comment token and walk

### ISSUE THREAD

**Issue by attliaLin** [sssooonnnggg/rslua#1]
Nice work!
It will be nice to support comments also. Maybe can be a config option.

**Comment by sssooonnnggg** [comment]
ok，后续会加上会在ast里加上comment

**Comment by sssooonnnggg** [comment]
Done

**Comment by attliaLin** [comment]
`self.next_and_skip_comment();` will skip comment when parse, so it will miss some comments.

**Comment by sssooonnnggg** [comment]
> `self.next_and_skip_comment();` will skip comment when parse, so it will miss some comments.
> 
> @sssooonnnggg

是的，我还没想好如何在ast里完整保存注释信息，在paser会丢掉statment之外的部分注释，比如table定义里的注释。但是在lexer阶段注释信息完整的。如果有好的想法欢迎提交pr~
@attliaLin
