### ISSUE TITLE
Can not identify the comment correcly.

### ISSUE THREAD

**Issue by Rose1917** [sssooonnnggg/rslua#2]
Thanks for your nice work first. 
But I noticed when a statement does not end with a comma, the ast will not identify more comments any longer.

Take the test/lua2lua for example:
![image](https://user-images.githubusercontent.com/49433992/197445654-7d295250-54cd-4348-b7b1-0c3a45775148.png)
When every statements end with a semicolon， everything works well. The output is asfollow:
![image](https://user-images.githubusercontent.com/49433992/197445869-210bce2d-a208-4d62-956f-af6e9ac29160.png)

But when one of the statement lack a semicolon, the comments will not be identified.
![image](https://user-images.githubusercontent.com/49433992/197445976-0f307b8b-abe0-4484-9592-0d83df4229db.png)
Here is the result
![image](https://user-images.githubusercontent.com/49433992/197446026-8591a8e3-35d4-4c67-b752-e29a8eb3980e.png)

**Comment by sssooonnnggg** [comment]
It seems a bug when parsing tokens with comments, I will fix it later.

**Comment by Rose1917** [comment]
Hi,I noticed you have made some commits recently. Maybe the comment bug has already been fixed in the new version? if yes, will this new version be published in the crates.io?

**Comment by Rose1917** [comment]
Thanks! Great Job. looking forward to more new features!
