### ISSUE TITLE
Version 0.2.7 seems to import some new errors...

### ISSUE THREAD

**Issue by Rose1917** [sssooonnnggg/rslua#4]
It is me again. 
Recently i am doing some work based on this excellent and concise library. 
And after i post an issue last time, i noticed you released a new version on crates.io. i.e 0.2.7 soon.

But it seems some new errors have been imported.

When i put some comment before an if-else statement, the parse process will fail.

For example:
![image](https://user-images.githubusercontent.com/49433992/204234596-546e4957-0b4f-469f-9588-6001d853fbf8.png)

This code snippest should be acceptable for lua5.3.
Thanks.

**Comment by Rose1917** [comment]
ADD: the error report. 
![image](https://user-images.githubusercontent.com/49433992/204250989-4b047505-accd-4898-bc4c-8d0b26042fee.png)
I believe this is enough for you to find out the error.
Looking forward to your response.

**Comment by Rose1917** [comment]
Emm, it seems I have found where the bug originates...

**Comment by sssooonnnggg** [comment]
Thanks for addressing this, will merge you PR to master branch and publish a new version.
